site_name: HTCondor-CE Documentation
site_url: https://htcondor.github.io/htcondor-ce
repo_url: https://github.com/htcondor/htcondor-ce/
edit_uri: edit/docs/docs/

theme:
  name: material
  favicon: img/favicon-32x32.png
  features:
    - navigation.tabs  # Split top-level nav items into their own menu at the top of the pages
    - toc.integrate    # integrate the table of contents into the left nav
    - navigation.top   # adds back-to-top button that appears when scrolling up

extra_css:
  - css/superfences.css
  - css/extra.css

nav:
- Home:
  - 'Overview': 'index.md'
  - 'Architecture': 'architecture.md'
- HTCondor-CE 6:
  - Installation: 'v6/installation/htcondor-ce.md'
  - Configuration:
    - Authentication: 'v6/configuration/authentication.md'
    - Local Batch System: 'v6/configuration/local-batch-system.md'
    - Job Router:
      - Overview: 'v6/configuration/job-router-overview.md'
      - Writing Job Routes: 'v6/configuration/writing-job-routes.md'
      - For HTCondor Batch Systems: 'v6/configuration/htcondor-routes.md'
      - For Non-HTCondor Batch Systems: 'v6/configuration/non-htcondor-routes.md'
    - Optional Configuration: 'v6/configuration/optional-configuration.md'
  - Operation: 'v6/operation.md'
  - Troubleshooting:
    - Common Issues: 'v6/troubleshooting/common-issues.md'
    - Debugging Tools: 'v6/troubleshooting/debugging-tools.md'
    - Helpful Logs: 'v6/troubleshooting/logs.md'
  - Central Grid Operations:
    - Submit Jobs Remotely: 'v6/remote-job-submission.md'
    - Remote Troubleshooting: 'v6/troubleshooting/remote-troubleshooting.md'
    - Install a Central Collector: 'v6/installation/central-collector.md'
  - Releases: 'v6/releases.md'
  - Reference: 'v6/reference.md'
- HTCondor-CE 5:
  - Installation: 'v5/installation/htcondor-ce.md'
  - Configuration:
    - Authentication: 'v5/configuration/authentication.md'
    - Local Batch System: 'v5/configuration/local-batch-system.md'
    - Job Router:
      - Overview: 'v5/configuration/job-router-overview.md'
      - Writing Job Routes: 'v5/configuration/writing-job-routes.md'
      - For HTCondor Batch Systems: 'v5/configuration/htcondor-routes.md'
      - For Non-HTCondor Batch Systems: 'v5/configuration/non-htcondor-routes.md'
    - Optional Configuration: 'v5/configuration/optional-configuration.md'
  - Operation: 'v5/operation.md'
  - Troubleshooting:
    - Common Issues: 'v5/troubleshooting/common-issues.md'
    - Debugging Tools: 'v5/troubleshooting/debugging-tools.md'
    - Helpful Logs: 'v5/troubleshooting/logs.md'
  - Central Grid Operations:
    - Submit Jobs Remotely: 'v5/remote-job-submission.md'
    - Remote Troubleshooting: 'v5/troubleshooting/remote-troubleshooting.md'
    - Install a Central Collector: 'v5/installation/central-collector.md'
  - Releases: 'v5/releases.md'
  - Reference: 'v5/reference.md'
- HTCondor-CE 4:
  - Installation: 'v4/installation/htcondor-ce.md'
  - Batch System Integration: 'v4/batch-system-integration.md'
  - Verification: 'v4/verification.md'
  - Troubleshooting: 'v4/troubleshooting/troubleshooting.md'
  - Central Grid Operations:
    - Submit Jobs Remotely: 'v4/remote-job-submission.md'
    - Remote Troubleshooting: 'v4/troubleshooting/remote-troubleshooting.md'
    - Install a Central Collector: 'v4/installation/central-collector.md'
  - Releases: 'v4/releases.md'
  - Reference: 'v4/reference.md'
- HTCondor-CE 3:
  - Installation: 'v3/installation/htcondor-ce.md'
  - Batch System Integration: 'v3/batch-system-integration.md'
  - Verification: 'v3/verification.md'
  - Troubleshooting: 'v3/troubleshooting/troubleshooting.md'
  - Releases: 'v3/releases.md'
  - Reference: 'v3/reference.md'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: False
  - toc:
      permalink: True
  - pymdownx.tabbed
  - pymdownx.superfences

plugins:
  - search
  - redirects:
      redirect_maps:
        'v6/verification.md': 'v6/operation.md'

