site_name: HTCondor-CE Documentation
site_url: https://htcondor.github.io/htcondor-ce
repo_url: https://github.com/htcondor/htcondor-ce/
edit_uri: edit/docs/docs/

theme:
  name: material
  favicon: img/favicon-32x32.png
  features:
    - navigation.tabs  # Split top-level nav items into their own menu at the top of the pages
    - toc.integrate    # integrate the table of contents into the left nav
    - navigation.top   # adds back-to-top button that appears when scrolling up

extra_css:
  - css/superfences.css
  - css/extra.css

nav:
- Home:
  - 'Overview': 'index.md'
  - 'Architecture': 'architecture.md'
- HTCondor-CE 23:
  - Installation: 'v23/installation/htcondor-ce.md'
  - Configuration:
    - Authentication: 'v23/configuration/authentication.md'
    - Local Batch System: 'v23/configuration/local-batch-system.md'
    - Job Router:
      - Overview: 'v23/configuration/job-router-overview.md'
      - Writing Job Routes: 'v23/configuration/writing-job-routes.md'
      - For HTCondor Batch Systems: 'v23/configuration/htcondor-routes.md'
      - For Non-HTCondor Batch Systems: 'v23/configuration/non-htcondor-routes.md'
    - Optional Configuration: 'v23/configuration/optional-configuration.md'
  - Operation: 'v23/operation.md'
  - Troubleshooting:
    - Common Issues: 'v23/troubleshooting/common-issues.md'
    - Debugging Tools: 'v23/troubleshooting/debugging-tools.md'
    - Helpful Logs: 'v23/troubleshooting/logs.md'
  - Central Grid Operations:
    - Submit Jobs Remotely: 'v23/remote-job-submission.md'
    - Remote Troubleshooting: 'v23/troubleshooting/remote-troubleshooting.md'
    - Install a Central Collector: 'v23/installation/central-collector.md'
  - Releases: 'v23/releases.md'
  - Reference: 'v23/reference.md'
- HTCondor-CE 6:
  - Installation: 'v6/installation/htcondor-ce.md'
  - Configuration:
    - Authentication: 'v6/configuration/authentication.md'
    - Local Batch System: 'v6/configuration/local-batch-system.md'
    - Job Router:
      - Overview: 'v6/configuration/job-router-overview.md'
      - Writing Job Routes: 'v6/configuration/writing-job-routes.md'
      - For HTCondor Batch Systems: 'v6/configuration/htcondor-routes.md'
      - For Non-HTCondor Batch Systems: 'v6/configuration/non-htcondor-routes.md'
    - Optional Configuration: 'v6/configuration/optional-configuration.md'
  - Operation: 'v6/operation.md'
  - Troubleshooting:
    - Common Issues: 'v6/troubleshooting/common-issues.md'
    - Debugging Tools: 'v6/troubleshooting/debugging-tools.md'
    - Helpful Logs: 'v6/troubleshooting/logs.md'
  - Central Grid Operations:
    - Submit Jobs Remotely: 'v6/remote-job-submission.md'
    - Remote Troubleshooting: 'v6/troubleshooting/remote-troubleshooting.md'
    - Install a Central Collector: 'v6/installation/central-collector.md'
  - Releases: 'v6/releases.md'
  - Reference: 'v6/reference.md'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: False
  - toc:
      permalink: True
  - pymdownx.tabbed
  - pymdownx.superfences

plugins:
  - search
  - redirects:
      redirect_maps:
        'v23/verification.md': 'v23/operation.md'

